<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>farmer side</title>
    <link rel="stylesheet" href="FA.css">
</head>
<body>
    <p align='center' class='title'><b>Farmer</b></p><br><br><br><br><br>
    <p align = 'center'> 
        <button type="submit" style="color:rgb(10, 7, 7);"><a href="farmer_details.php">AGRICLUTURE</a></button><br><br><br><br><br><br><br><br>
    </p>
       <h4>OR</h4><br><br><br><br><br><br><br><br>
    <p align='center'>
        <button type="submit" style="color:black;"><a href="farmer_details1.php">AQUACLUTURE</a></button>
    </p>
</body>
</html>